# Generated by Django 5.2 on 2025-05-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_usuario_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='ano_de_popublicacao',
            new_name='ano_de_publicacao',
        ),
    ]
