# Generated by Django 5.2 on 2025-05-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_rename_ano_de_popublicacao_livros_ano_de_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nome',
            field=models.CharField(default='teste@exemplo.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='telefone',
            field=models.IntegerField(default='000000000'),
            preserve_default=False,
        ),
    ]
