# Generated by Django 5.2 on 2025-05-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_remove_emprestimo_usuario_emprestimo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livros.usuario'),
            preserve_default=False,
        ),
    ]
